subtitle = 'Subtitle here'
description = 'Description'
[comment]
enable = true
disable_on_local = true
only_on_pages = false
repo = 'alohaia/alohaia.github.io'
issue_term = "title" # pathname | url | title | og:title
theme = "github-light"
[quote]
enable = 'jinrishici' # or 'rainbow'
[music]
enable = false
server = 'netease'
type = 'playlist'
#id = 2362969974
id = '6822976600'
mini = false
fixed = false
list_folded = true
autoplay = false
volume = 0.4
theme = '#b7daff'
order = 'random'
loop = 'all'
preload = 'auto'
mutex = true
[scrollbar]
style = "custom"
[pjax]
enable = false
[[header]]
